config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount ActionCable.server => "/cable"

  root to: 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact', as: :contact

  resources :users, only: [ :index, :show ] do
    resources :messages, only: [ :new, :create ]
  end

  resources :posts, only: [ :index, :new, :create, :destroy ] do
    resources :excludeds, only: [ :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/excluded.rb
class Excluded < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  after_create :send_notif

  private

  def send_notif
    ChatChannel.broadcast_to(
      "received_messages_#{recipient_id}",
      message: self,
      sender_id: sender_id,
      message_html: ApplicationController.renderer.render(partial: "messages/message", locals: { message: self, current_user_role: :recipient })
    )
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :excluded, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :job, presence: true
  validates :email, presence: true
  validates :photo, presence: true
  has_many :posts
  has_many :messages
  has_one_attached :photo
  has_many :excluded, dependent: :destroy



  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  # has_many :sent_messages, class_name: "Message", foreign_key: "sender_id"
  # has_many :received_messages, class_name: "Message", foreign_key: "recipient_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_messages_path
  before_action :configure_permitted_parameters, if: :devise_controller?

  def set_messages_path
    @message_path = "#"
    if current_user && Message.where(recipient: current_user).count >= 1
      @message_path = new_user_message_path(Message.where(recipient: current_user).last.sender)
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :job, :bio, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :job, :bio, :photo])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/excludeds_controller.rb
class ExcludedsController < ApplicationController
  def create
    @excluded = Excluded.new
    @excluded.user = current_user
    @excluded.post = Post.find(params[:post_id])
    @excluded.save
    @post = @excluded.post
    respond_to do |format|
      format.html { redirect_to posts_path }
      format.js # <-- will render `app/views/reviews/create.js.erb`
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
    @user = User.find(params[:user_id])
    user_id = params[:user_id]
    @messages = Message.where('(sender_id  = ? AND recipient_id = ?) OR (sender_id  = ? AND recipient_id = ?)', current_user.id, user_id, user_id, current_user.id)
    @messages = @messages.order("created_at ASC").all
    array = []
    @messages2 = Message.where('(sender_id  = ? OR recipient_id = ?)', current_user.id, current_user.id)
    @messages2.each do |m|
      if m.sender_id == current_user.id
        array << m.recipient_id
      else
        array << m.sender_id
      end
    end
    @chats = []
    array.uniq.each do |id|
      user = User.find(id)
      @chats << { id: id, name: user.first_name }
    end
  end

  def create
    @message = Message.new(message_params)
    @message.sender = current_user
    @message.recipient = User.find(params[:user_id])
    if @message.save
      respond_to do |format|
        format.js
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(:text)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
require 'date'

class PostsController < ApplicationController

  def index
    @excludeds = Excluded.where(user_id: current_user)
    @excluded_posts = []

    @excludeds.each do |excluded|
      @excluded_posts << excluded.post
    end

    @expired_posts = []
    @all_posts = Post.all.order(created_at: :desc).to_ary

    @all_posts.each do |post|
      @expired_posts << post if post.expires_at < Time.zone.now
    end

    @posts = Post.all.order(created_at: :desc).to_ary - @excluded_posts - @expired_posts
    @community_posts = Post.where(category: 'Community').order(created_at: :desc).to_ary - @excluded_posts - @expired_posts
    @utility_posts = Post.where(category: 'Utility').order(created_at: :desc).to_ary - @excluded_posts - @expired_posts
    @expertise_posts = Post.where(category: 'Expertise').order(created_at: :desc).to_ary - @excluded_posts - @expired_posts
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      @post.expires_at = @post.created_at + 86400
      @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to posts_path
    else
      redirect_to post_path(@post)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :category, :content, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:range].present?
      @users = User.where.not(id: current_user.id).near([params[:latitude], params[:longitude]], params[:range])
    else
      @users = User.where.not(id: current_user.id).geocoded
    end
    @markers = @users.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { user: user }),
        image_url: helpers.asset_url('pin-map.svg'),
        id: user.id
      }
    end
    if params[:onlyUsers]
      render json: {
        html: render_to_string(partial: "users/map_and_list")
      }
    else
      render "users/index"
    end

  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/excludeds/create.js.erb
var card = document.querySelector("#post-<%= @post.id %>");
card.classList.add("animated", "fadeOutUp");
setTimeout(() => {card.remove()}, 500);
// card.remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">


    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body class="<%= params[:controller]%>-<%=params[:action] %>">
    <%= render 'shared/flashes' %>
    <% if current_page?(root_path) %>
      <%= render 'shared/navbar' %>
    <% end %>

    <div class="<%= "all-contenu d-flex" unless current_page?(root_path) %>">
      <% unless current_page?(root_path) %>
        <%= render 'shared/navbar2' %>
      <% end %>
      <div class="<%= "page-contenu" unless current_page?(root_path) %>">
        <div class="page_banner">
          <%= yield %>
        </div>
      </div>
    </div>

    <% if current_page?(root_path) %>
      <%= render 'shared/footer' %>
    <% end %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <input type="hidden" id="user-id" value="<%= current_user&.id %>" />
  </body>
</html>

app/views/messages/_message.html.erb
<div class="light-container m-2 <%= 'darker' if current_user_role == :recipient %>">

  <% if message.sender.photo.attached? %>
    <div class="avatar-small"><%= cl_image_tag message.sender.photo.key,crop: :thumb, gravity: :face, height:40, width:40%></div>
    <% end %>
  <p class="mb-1">
    <h4 class="middle-size"><%= message.sender.first_name %></h4>
    <p class="small-size" id="blue"><%= message.text %>
    </p>
  </p>
  <div class="text-right">
    <small>
      <p><%= message.created_at.time.to_formatted_s(:short) %></p>
    </small>
  </div>
</div>

app/views/messages/create.js.erb
function addMessage(messageHTML) {
  const messages = document.querySelector('.messages-container');
  messages.insertAdjacentHTML('beforeend', messageHTML);
  messages.scrollTop = messages.scrollHeight;
  document.querySelector("#new_message").reset();
}

console.log('test')
addMessage('<%= j render "message", message: @message, current_user_role: @message.sender == current_user ? :sender : :recipient %>');

app/views/messages/new.html.erb
<div class="chatroom">

  <div class="chat-header">
    <h3 class="middle-size" id="corail">Knock-Knock Chat with <%= @user.first_name %></h3>
  </div>

<!--   <div class="chat-welcome">
    <%# if Message.where(recipient: @user, sender: current_user).empty? %>
      <p>Start to chat!</p>
    <%# end %>
  </div> -->


  <div class="knock-chat-container">
    <div class="messages-container">
      <div class="welcome-container">
        <%= image_tag "logo-knock-couleur.svg",width:150 %>
        <h3 class="small-size mt-2" >Start chatting!</h3>
      </div>
      <% @messages.each do |message| %>
        <%= render 'message', message: message, current_user_role: message.sender == current_user ? :sender : :recipient %>
      <% end %>
    </div>

    <div class="form-chat">
          <%= simple_form_for([@user, @message], remote: true) do |f| %>
            <%= f.input :text, placeholder: "Type your message", label: false %>
            <%#= f.submit "KNOCK", class: "btn-submit", id: "submit-button" %>
            <%= button_tag(:type => 'submit', :class => 'btn-submit', id: 'submit-button') do %>
             <i class="fas fa-paper-plane"></i>
            <% end %>
          <% end %>
    </div>
  </div>


</div>


<input type="hidden" id="recipient-id" value="<%= @user.id %>">

<div class="image-fond-message">
    <%= image_tag "message-illu.svg" %>
</div>

app/views/pages/home.html.erb
<div class="home_banner">

  <div class="container ">
    <div class="row" style="height: 100vh; align-items: center;">
      <div class="col-6 offset-1 presentation-home">
        <h1 class ="big-size">Your localised network of digital nomad workers</h1>
        <h3 class="middle-size anime-js"><span id="banner-typed-text"></span></h3>
          <div class= "mt-4 ">
            <%= link_to render("shared/button", text: "DISCOVER"), users_path %>
          </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row d-flex justify-content-between mt-5">
    <div class="card-presentation">
      <%= image_tag "interact.svg" %>
      <h3>Interact</h3>
      <br>
      <p>Forget your usual day of work alone at home 🧑🏻‍💻</p>
      <p>Get interactions with digital nomad workers around you 🌀</p>
    </div>

    <div class="card-presentation">
      <%= image_tag "expertise.svg" %>
      <h3>Expertise</h3>
      <br>
      <p>Stuck in a project... 💣</p>
      <p>Never again! Get help from experts around you 🧙🏼‍♂️</p>
    </div>

    <div class="card-presentation">
      <%= image_tag "social.svg" %>
      <h3>Social</h3>
      <br>
      <p>Start to discuss with a colleague 🤓</p>
      <p>End up with a new friend! 🤩</p>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="big-container">

  <div class= "top-banner">
    <h3 class="small-size text-right p-3 " id="corail">  <%=Date.today.to_s(:long) %></h3>
  </div>

  <ul class="nav nav-tabs tabs-underlined format-onglets ml-5" id="myTab" role="tablist" style="position: relative;">
    <li class="nav-item">
      <a class="tabs-borders tab-underlined nav-link active" id="all-tab" data-toggle="tab" href="#all" role="tab" aria-controls="all" aria-selected="true">All</a>
    </li>
    <li class="nav-item">
      <a class="tabs-borders tab-underlined nav-link" id="community-tab" data-toggle="tab" href="#community" role="tab" aria-controls="community" aria-selected="false">Community</a>
    </li>
    <li class="nav-item">
      <a class="tabs-borders tab-underlined nav-link" id="utility-tab" data-toggle="tab" href="#utility" role="tab" aria-controls="utility" aria-selected="false">Utility</a>
    </li>
    <li class="nav-item">
      <a class="tabs-borders tab-underlined nav-link" id="expertise-tab" data-toggle="tab" href="#expertise" role="tab" aria-controls="expertise" aria-selected="false">Expertise</a>
    </li>
    <li>
      <%= link_to "New Post", new_post_path, class: "btn-secondary new-post" %>
    </li>
  </ul>



  <div class="tab-content" id="myTabContent">

    <div class="tab-pane fade show active posts-container" id="all" role="tabpanel" aria-labelledby="all-tab">
      <%= render partial: 'posts/tabs/content_tabs', locals: { posts: @posts } %>
    </div>

    <div class="tab-pane fade posts-container" id="community" role="tabpanel" aria-labelledby="community-tab">
      <%= render partial: 'posts/tabs/content_tabs', locals: { posts: @community_posts } %>
    </div>

    <div class="tab-pane fade posts-container" id="utility" role="tabpanel" aria-labelledby="utility-tab">
      <%= render partial: 'posts/tabs/content_tabs', locals: { posts: @utility_posts } %>
    </div>

    <div class="tab-pane fade posts-container" id="expertise" role="tabpanel" aria-labelledby="expertise-tab">
      <%= render partial: 'posts/tabs/content_tabs', locals: { posts: @expertise_posts } %>
    </div>

  </div>

</div>

app/views/posts/new.html.erb
<h1>Create a Post</h1>
<%= simple_form_for [@post] do |f| %>
  <%= f.input :title %>
  <%= f.input :category %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>
<p><%= link_to "See all posts", posts_path  %></p>

app/views/posts/tabs/_content_tabs.html.erb
<div class="cards-p">
  <% posts.each do |post| %>
    <div class="card-post" id="post-<%= post.id %>">
      <%= link_to post_excludeds_path(post), method: :post, remote: true, id: "bomb" do %>
        <%= image_tag "croix.svg" %>
      <% end %>

        <div class="cat-remove">
          <h2 class="category"><%= post.category %></h2>
          <% if ((post.expires_at - Time.zone.now)/86400*24) > 1 %>
            <% hours_remaining = ((post.expires_at - Time.zone.now)/86400*24).to_i %>
            <div><progress id="file" max="100" value="<%= [100 - (post.expires_at - Time.zone.now) / 86400 * 100, 10].max %>" content="<%= hours_remaining %>h"></progress></div>
          <% else %>
            <% hours_remaining2 = (((post.expires_at - Time.zone.now)/86400*24)*60).to_i %>
            <div><progress id="file" max="100" value="<%= [100 - (post.expires_at - Time.zone.now) / 86400 * 100, 10].max %>" content="<%= hours_remaining2 %>m"></progress></div>
          <% end %>
        </div>
        <div class="card-center">

          <div class="card-post-info d-flex mb-2 ">
            <div class ="p-2">
              <% if post.user.photo.attached? %>
              <div class="avatar-post"><%= cl_image_tag post.user.photo.key, height:50, width:50 %></div>
              <% end %>
            </div>
            <div class ="ml-3 mt-3">
              <h4 class="user"><%= post.user.first_name %></h4>
              <h2 class="xsmall-size"><%= post.user.job.upcase %></h2>
            </div>
          </div>

          <div class="d-flex justify-content-between ">
              <h1 class="small-size"><%= post.title %></h1>
          </div>
          <div class="card-post-content" >
            <p class="small-size" id="blue"><%= post.content.truncate(200) %></p>
          </div>
      </div>

      <div class="div-delete">
        <% if post.user == current_user %>
          <%= link_to "Delete my post", post_path(post), data: { confirm: "Are you sure you want to delete your post?" }, method: :delete, class: "btn-4tiary-delete" %>
        <% else %>
          <%= link_to "Start chat", new_user_message_path(post.user), class: "btn-4tiary-chat" %>
        <% end %>
      </div>

    </div>
     <% end %>
    </div>

app/views/shared/_button.html.erb
<div class="btn-primari d-flex align-items-center justify-content-between">
  <h5 class ="small-size m-0 text-align-end flex-grow p-2"><%= text %> </h5>
  <div class=" ml-3"><%= image_tag "fleche-orange.svg", alt: "alttext", height: "30px", class: 'fleche' %> </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-static-links">
    <%= link_to 'about', about_path %>
    <%= link_to 'contact', contact_path %>
  </div>
  <div class="footer-links">
    <a href="https://github.com/martin-nl/knock-knock" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/nomadicworkers/" target="_blank"><i class="fab fa-instagram"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "knock-logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <h3 class ="small-size">
            <%= link_to "About", about_path, class: "nav-link" %>
          </h3>
        </li>
        <li class="nav-item">
          <h3 class ="small-size">
            <%= link_to "Contact", contact_path, class: "nav-link" %>
          </h3>
        </li>
        <li class="nav-item">
          <h3 class ="small-size">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </h3>
        </li>

       <% else %>
        <li class="nav-item active">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar2.html.erb
<% if user_signed_in? %>
  <div class="navbar-frame ">
    <div class="profil">
      <div class="m-4 text-center" >
        <%= link_to root_path do %>
          <%= image_tag "logo-blanc.svg", width:170%>
        <% end %>
      </div>
      <% if current_user.photo.attached? %>
        <div>
          <div class="text-center">
            <%= cl_image_tag current_user.photo.key, crop: :thumb, gravity: :face, class: "small-avatar"%>
          </div>
          <div>
            <h2 class="xsmall-size text-center pt-3 m-0 " id="white"><%=current_user.first_name.upcase %> <%=current_user.last_name.upcase %> </h2>
            <p class="text-center small-size pt-1" id="white"><%=current_user.job%></p>
          </div>
        </div>
      <% end %>
    </div>

    <div class="menu flex-grow-1 p-4">
      <%= link_to users_path, class: "menu-title mt-5 d-flex #{'active' if request.path == '/users'}" do %>
        <div><%= image_tag "discover.svg", class: "icone_menu" %></div>
        <p id="white" class="menu-titles ml-4">Discover</p>
      <% end %>
      <%= link_to posts_path, class: "menu-title d-flex #{'active' if request.path == '/posts'}" do %>
        <div><%= image_tag "feed.svg", class: "icone_menu" %></div>
        <p id="white" class="menu-titles ml-4">Feed</p>
      <% end %>
      <div class="menu-title d-flex">
        <div id="notifications" class="notification-alert">
          <%= link_to @message_path do %>
            <div><%= image_tag "chat.svg", class: "icone_menu" %></div>
          <% end %>
          <div class="badge-notification"></div>
        </div>
        <p id="white" class="menu-titles ml-4">Messages</p>
      </div>


    <div class="conversations">
      <% if params[:controller] == "messages" %>
        <ul>
          <% @chats.each do |chat| %>
            <li><%= link_to chat[:name], new_user_message_path(chat[:id]) %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <%= link_to root_path do %>
      <div class="logout"><%= image_tag "logout.svg", width:45%></div>
    <% end %>
  </div>
</div>
<% else %>
  <div class="navbar-frame p-4 ">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "knock-logo.png" %>
    <% end %>
  </div>
<% end %>

app/views/users/_info_window.html.erb
<%= link_to(user_path(user)) do %>
  <div class="map-user-container">
    <div class="d-flex justify-content-center p-2">
      <% if user.photo.attached? %>
        <div class="avatar-small"><%= cl_image_tag user.photo.key, height:50, width:50 %></div>
      <% end %>
      <div class="text-left p-2">
        <h4 class="small-size"><%= user.first_name %></h4>
        <h2 class="xsmall-size"><%= user.job.upcase %></h2>
        <btn class="btn-link">see the profile</btn>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_map_and_list.html.erb
<div class="results">
  <% if params[:range].present? %>
    <h1 id="mid-purple"class="small-size"><%= pluralize @users.size, "knockie" %> around you</h1>
  <% else %>
    <h1 id="mid-purple"class="small-size">Find knockies nearby</h1>
  <% end %>
</div>
<div class="user-index-main-content">
  <div class="main-content-map">
    <div class="map-box"
      id="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      <div class="map-hover d-none">
        <div class="d-flex justify-content-center text-center">
          <div class="spinner-grow" style="width: 3rem; height: 3rem; color: $corail;" role="status">
            <span class="sr-only" style="">Loading...</span>
          </div>
        </div>
      </div>
    </div>
    <div class="btn-localisation d-flex  justify-content-center mt-1">
      <button class='btn-secondary localize' data-range="2">2 kms</button>
      <button class='btn-secondary localize' data-range="5">5 kms </button>
      <button class='btn-secondary localize' data-range="10">10 kms</button>
    </div>
  </div>

  <div class ="main-content-users-list">
    <div class="cards scrolling">
      <% @users.each do |user| %>
        <div class="card-index-user user-<%= user.id %>" data-user-id="<%= user.id %>">
          <%= link_to(user_path(user)) do %>
            <div class="d-flex">
              <div>
                <%= cl_image_tag user.photo.key, crop: :thumb, gravity: :face, class: "xsmall-avatar" %>
              </div>
              <div class="card-index-user-info">
                <div class="username">
                  <h4 class="small-size"><%= user.first_name %></h4>
                  <% if params[:range].present? %>
                  <span><i class="fas fa-map-marker-alt"></i> <%= ((Geocoder::Calculations.distance_between([params[:longitude],params[:latitude]], [user.longitude, user.latitude])).round(2)) %>km</span>
                  <% end %>
                </div>
                <h2 class ="xsmall-size"><%= user.job.upcase %></h2>
                <h3 class ="xsmall-size"><%= user.status %></h2>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_map_info_window.html.erb
<div class="info-window">
  <%= user.name %>
</div>

app/views/users/index.html.erb
<div class="big-container user-index-right-container">
    <div class= "top-banner">
      <h3 class="small-size text-right p-3 " id="corail">  <%=Date.today.to_s(:long) %></h3>
    </div>

    <div class="welcome">
      <h3 class="middle-size" id="white">Welcome back <span><%= current_user.first_name.capitalize %></span>!</h3>
      <div class="image-welcome"><%= image_tag "test-index.svg", width:250 %></div>
    </div>

    <div id="map_and_list">
      <%= render "map_and_list" %>
    </div>
</div>